# Generated by Django 4.2.7 on 2026-01-20 09:49

from decimal import Decimal
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Sport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('description', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('icon', models.CharField(blank=True, max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Вид спорта',
                'verbose_name_plural': 'Виды спорта',
            },
        ),
        migrations.CreateModel(
            name='League',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('country', models.CharField(max_length=100)),
                ('logo_url', models.CharField(blank=True, max_length=500)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('sport', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='leagues', to='events.sport')),
            ],
            options={
                'verbose_name': 'Лига/Турнир',
                'verbose_name_plural': 'Лиги/Турниры',
                'unique_together': {('name', 'sport', 'country')},
            },
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('start_time', models.DateTimeField()),
                ('end_time', models.DateTimeField()),
                ('status', models.CharField(choices=[('scheduled', 'Запланировано'), ('live', 'В прямом эфире'), ('finished', 'Завершено'), ('cancelled', 'Отменено'), ('postponed', 'Перенесено')], default='scheduled', max_length=20)),
                ('team_a', models.CharField(max_length=100)),
                ('team_b', models.CharField(max_length=100)),
                ('team_a_logo_url', models.CharField(blank=True, max_length=500)),
                ('team_b_logo_url', models.CharField(blank=True, max_length=500)),
                ('result', models.JSONField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('league', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to='events.league')),
            ],
            options={
                'verbose_name': 'Спортивное событие',
                'verbose_name_plural': 'Спортивные события',
                'ordering': ['start_time'],
            },
        ),
        migrations.CreateModel(
            name='Odd',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('odd_type', models.CharField(choices=[('win_a', 'Победа команды A'), ('draw', 'Ничья'), ('win_b', 'Победа команды B'), ('total_over', 'Тотал больше'), ('total_under', 'Тотал меньше'), ('handicap_a', 'Фора команды A'), ('handicap_b', 'Фора команды B')], max_length=50)),
                ('value', models.DecimalField(decimal_places=2, max_digits=5, validators=[django.core.validators.MinValueValidator(Decimal('1.01'))])),
                ('parameters', models.JSONField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='odds', to='events.event')),
            ],
            options={
                'verbose_name': 'Коэффициент',
                'verbose_name_plural': 'Коэффициенты',
                'unique_together': {('event', 'odd_type', 'parameters')},
            },
        ),
    ]
