# Generated by Django 4.2.7 on 2026-01-20 09:49

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('events', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Bet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(10.0)])),
                ('potential_win', models.DecimalField(decimal_places=2, max_digits=12)),
                ('actual_win', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('status', models.CharField(choices=[('pending', 'Ожидает'), ('won', 'Выиграна'), ('lost', 'Проиграна'), ('cancelled', 'Отменена'), ('refunded', 'Возвращена')], default='pending', max_length=20)),
                ('is_live', models.BooleanField(default=False)),
                ('placed_at', models.DateTimeField(auto_now_add=True)),
                ('settled_at', models.DateTimeField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bets', to='events.event')),
                ('odd', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bets', to='events.odd')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bets', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Ставка',
                'verbose_name_plural': 'Ставки',
                'ordering': ['-placed_at'],
            },
        ),
    ]
